### ISSUE TITLE
Install issue with qiskit-aer

### ISSUE THREAD

**Issue by willzeng** [unitaryfund/wigners_friend#41]
I've got the same poetry install issue with this package as with metriq-gym see this issue: https://github.com/unitaryfund/metriq-gym/issues/17

Any suggestions on how to get poetry to install `qiskit-aer` @vprusso ?

**Comment by vprusso** [comment]
Give this approach:
https://github.com/unitaryfund/metriq-gym/issues/17#issuecomment-2466723643

A go and let me know if that resolves the issue. We can also triage quickly together. I do have both of these projects running on at least 3 different MacOS instances (both M1 and Intel-based) so I think it's likely a `poetry` issue.

**Comment by willzeng** [comment]
As described in https://github.com/unitaryfund/metriq-gym/issues/17 the issue is with `qiskit-aer` not yet building properly with Python 3.13. Using Python 3.12 avoids this issue.

**Comment by willzeng** [comment]
Fixed by f7a54031a2eed7746bb0b06b6d3e08d8f96af698
