### ISSUE TITLE
Why do we RemoveBarriers in the demo notebook

### ISSUE THREAD

**Issue by willzeng** [unitaryfund/wigners_friend#43]
In https://github.com/unitaryfund/wigners_friend/blob/main/notebooks/demo.ipynb we have the code:
```
        # Create circuits for each EWFS setting.
        # Note, we remove barriers in the Qiskit circuit.
        for alice, bob in all_experiment_combos:
            circuits[(alice, bob)] = RemoveBarriers()(
                ewfs(alice, bob, strategy, ANGLES, BETA, charlie_size, 1)
            )
```

Why is `RemoveBarriers` called here? We still get violations without it and we want the barriers to facilitate compilation, e.g. from #42.

It looks to me like the `RemoveBarriers` call can be safely removed. Any reason not to @vprusso @FarLab ?

**Comment by willzeng** [comment]
Any update on this @vprusso ?

**Comment by vprusso** [comment]
Apologies, I thought I responded to this. Yes, I agree that we get rid of RemoveBarriers. I can go ahead and assign this to myself and carry that out.

**Comment by willzeng** [comment]
I can take it. Will do so now
