### ISSUE TITLE
Test: Add unit tests for violation values vs. mu for state

### ISSUE THREAD

**Issue by vprusso** [unitaryfund/wigners_friend#7]
Ideally, we should:

- Add a `tests/` directory for unit tests
- Extract the relevant fields from the spreadsheet in `data/` and place into Python dictionary
- Loop over values of `mu` and see if the values we obtain on the LHS of the violations align with the values obtained in the spreadsheet
- Finally, we should remove the spreadsheet and `data/` folder (assuming we abstract this into some Python data structure.  

Note also that to attain values similar to the ones in the `data/` folder (and to be able to run the tests in a reasonable amount of time) we should do so on a simulator with a fairly high number of shots (i.e. `100_000`). 

Note as well that we will most likely need to check the values to be within some acceptable threshold of agreement.

**Comment by willzeng** [comment]
Closed as stale
